### ISSUE TITLE
Compatibility with nested tables- error during extracting tables with header toggle on

### ISSUE THREAD

**Issue by jyosnaphilip** [SiddhantSadangi/pdf-workdesk#2]
Duplicate column names found: ['', '', '', '', '', '', '', '', '', '']
Traceback (most recent call last):
  `File "/mount/src/pdf-workdesk/app.py", line 180, in <module>
    utils.extract_tables(
  File "/mount/src/pdf-workdesk/utils.py", line 347, in extract_tables
    st.write(
  File "/home/adminuser/venv/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py", line 408, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.10/site-packages/streamlit/elements/write.py", line 415, in write
    self.dg.dataframe(arg)
  File "/home/adminuser/venv/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py", line 408, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.10/site-packages/streamlit/elements/arrow.py", line 523, in dataframe
    proto.data = dataframe_util.convert_pandas_df_to_arrow_bytes(data_df)
  File "/home/adminuser/venv/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 386, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4623, in pyarrow.lib.Table.from_pandas
  File "/home/adminuser/venv/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 572, in dataframe_to_arrays
    convert_fields) = _get_columns_to_convert(df, schema, preserve_index,
  File "/home/adminuser/venv/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 354, in _get_columns_to_convert
    raise ValueError(
ValueError: Duplicate column names found: ['', '', '', '', '', '', '', '', '', ['']`]
[table.pdf](https://github.com/user-attachments/files/16593675/table.pdf)

**Comment by SiddhantSadangi** [comment]
Hey @jyosnaphilip 👋 
Thank you for reporting this.

Unfortunately, the issue lies with the pdfplumber library, which is responsible for extracting tables. I recommend creating an issue in their repository: https://github.com/jsvine/pdfplumber/issues

Given the structure of this table, the best way to extract it would be to use either the `text` and `lines` or `lines` and `lines` strategies for vertical and horizontal extraction, respectively. You can turn off the `Header` option to avoid the `Duplicate column names` error.

I am closing this issue as I am unable to assist with this error. However, feel free to leave a comment if there's anything else I can help you with.
